# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 57b14a652be99d0161fdb39221d0350130dec9e96fb615160b715097cdf8d6ea3c3093d3b28dc88126162dacd394c75cc34fb2c3a917c5d69f869a80a402dee5

test:
  secret_key_base: 20ba05acab6f00bd63c6f270251505272e0e54b5d7c7b782100ba56fd42f7f60ba8e08f034c9d5f1f5f7552a628a4d468f62c5580b2d11f29083e7b0434094b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
