# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a11be22b997f95652e6799247ef4c3de6757629a4e44485a6f586e22c667917c81b1e7d0f00571cc47c928ab50c4648049a19e62327ddc79b549959912d69ce

test:
  secret_key_base: eb576468c7bddc478a7d61367745aa06d8d2056f7702ddc8a50adaf08a70b277de11e0e77885b70540dfaff3bdb92611350e129b65925a46ef88ca4777235efe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
